apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-svc
spec:
  selector:
    matchLabels:
      app: company-svc
  template:
    metadata:
      labels:
        app: company-svc
    spec:
      containers:
      - name: company-svc
        image: rafin160/companyimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s

---
apiVersion: v1
kind: Service
metadata:
  name: company-svc
spec:
  selector:
    app: company-svc
  ports:
  - port: 8081
    targetPort: 8081


