apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-svc
spec:
  selector:
    matchLabels:
      app: job-svc
  template:
    metadata:
      labels:
        app: job-svc
    spec:
      containers:
      - name: job-svc
        image: rafin160/jobimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s

---
apiVersion: v1
kind: Service
metadata:
  name: job-svc
spec:
  selector:
    app: job-svc
  ports:
  - port: 8082
    targetPort: 8082

