apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-svc
spec:
  selector:
    matchLabels:
      app: review-svc
  template:
    metadata:
      labels:
        app: review-svc
    spec:
      containers:
      - name: review-svc
        image: rafin160/reviewimg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s

---
apiVersion: v1
kind: Service
metadata:
  name: review-svc
spec:
  selector:
    app: review-svc
  ports:
  - port: 8083
    targetPort: 8083

