services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - mynetwork
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  configserver:
    image: configserverimg:latest
    container_name: configserver
    ports:
      - 8085:8085
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: serviceregimg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - mynetwork


  companyms:
    image: companyimg:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - configserver
    networks:
      - microservice-network
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  reviewms:
    image: reviewimg:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - configserver
    networks:
      - microservice-network
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: jobimg:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - servicereg
      - configserver
    networks:
      - microservice-network
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  gateway:
    image: gatewayimg:latest
    container_name: gateway
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  mynetwork:
    driver: bridge
  microservice-network:
    driver: bridge


volumes:
  postgres_data:
  pgadmin:
